package phpRecDB.helper.gui;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainFrame {

    public MainFrame() {
        lblHelpSnapshots.addMouseListener(new InstantTooltipMouseAdapter());
        lblHelpSnapshots.setToolTipText("<html>double click a snapshot to open it in system viewer<br><br>press DELTE-Key to remove a snapshot</html>");

        Border margin = new EmptyBorder(10, 10, 10, 10);
        pnlMediaSelection.setBorder(new CompoundBorder(pnlMediaSelection.getBorder(), margin));
        pnlConnection.setBorder(new CompoundBorder(pnlConnection.getBorder(), margin));
        pnlRecordInfo.setBorder(new CompoundBorder(pnlRecordInfo.getBorder(), margin));
        pnlSnapshots.setBorder(new CompoundBorder(pnlSnapshots.getBorder(), margin));
    }

    public JTable getTableMediaTitles() {
        return tableMediaTitles;
    }

    public JSlider getSliderTimeBar() {
        return sliderTimeBar;
    }

    public JLabel getLblCurrentTime() {
        return lblCurrentTime;
    }

    public JLabel getLblMediaInfo() {
        return lblMediaInfo;
    }

    public JLabel getLblLength() {
        return lblLength;
    }

    public JTextField getTfPath() {
        return tfPath;
    }

    public JButton getBtnChooseMedia() {
        return btnChooseMedia;
    }

    public JPanel getPnlMain() {
        return pnlMain;
    }

    public JPanel getPnlVlc() {
        return pnlVlc;
    }

    public JButton getBtnSnapshot() {
        return btnSnapshot;
    }

    public JButton getSendToPhpRecDb() {
        return btnSendToPhpRecDb;
    }

    public JPanel getPnlSnapshots() {
        return pnlSnapshots;
    }

    public JScrollPane getScrollbarSnapshots() {
        return scrollbarSnapshots;
    }

    public JList getListSnapshots() {
        return listSnapshots;
    }

    public JLabel getLblMediaTitleInfo() {
        return lblMediaTitleInfo;
    }

    public PlaceholderTextField getTfPhpRecDbUrl() {
        return tfPhpRecDbUrl;
    }

    public JButton getBtnConnect() {
        return btnConnect;
    }

    public JLabel getLblRecordInfo() {
        return lblRecordInfo;
    }

    public JButton getBtnPasteFromClipboard() {
        return btnPasteFromClipboard;
    }

    private JPanel pnlMain;
    private JPanel pnlConnection;
    private JPanel pnlVlc;
    private JPanel pnlMedia;
    private JPanel pnlLoadResource;
    private JButton btnChooseMedia;
    private JTextField tfPath;
    private JPanel pnlMediaTitleDetail;
    private JSlider sliderTimeBar;
    private JPanel pnlTimeBar;
    private JLabel lblLength;
    private JLabel lblCurrentTime;
    private JLabel lblMediaInfo;
    private JTable tableMediaTitles;
    private JButton btnSnapshot;
    private JButton btnSendToPhpRecDb;
    private JScrollPane scrollbarSnapshots;
    private JPanel pnlSnapshots;
    private JList listSnapshots;
    private JPanel pnlMediaTitleInfo;
    private JLabel lblMediaTitleInfo;
    private JPanel pnlMediaTitles;
    private PlaceholderTextField tfPhpRecDbUrl;
    private JButton btnConnect;
    private JLabel lblRecordInfo;
    private JButton btnPasteFromClipboard;
    private JLabel lblHelpSnapshots;
    private JPanel pnlMediaSelection;
    private JPanel pnlRecordInfo;

    public void resetUi() {
        lblMediaInfo.setText("");
        lblMediaTitleInfo.setText("");
        tfPhpRecDbUrl.setText("");

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new BorderLayout(0, 0));
        pnlMediaSelection = new JPanel();
        pnlMediaSelection.setLayout(new BorderLayout(0, 0));
        pnlMain.add(pnlMediaSelection, BorderLayout.CENTER);
        pnlMediaSelection.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Media Selection", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        pnlMedia = new JPanel();
        pnlMedia.setLayout(new BorderLayout(0, 0));
        pnlMediaSelection.add(pnlMedia, BorderLayout.CENTER);
        pnlMediaTitleDetail = new JPanel();
        pnlMediaTitleDetail.setLayout(new BorderLayout(0, 0));
        pnlMedia.add(pnlMediaTitleDetail, BorderLayout.EAST);
        pnlVlc = new JPanel();
        pnlVlc.setLayout(new BorderLayout(0, 0));
        pnlVlc.setMinimumSize(new Dimension(10, 10));
        pnlMediaTitleDetail.add(pnlVlc, BorderLayout.CENTER);
        pnlTimeBar = new JPanel();
        pnlTimeBar.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        pnlMediaTitleDetail.add(pnlTimeBar, BorderLayout.SOUTH);
        sliderTimeBar = new JSlider();
        pnlTimeBar.add(sliderTimeBar, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblLength = new JLabel();
        lblLength.setText("");
        pnlTimeBar.add(lblLength, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCurrentTime = new JLabel();
        lblCurrentTime.setText("");
        pnlTimeBar.add(lblCurrentTime, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pnlMediaTitleInfo = new JPanel();
        pnlMediaTitleInfo.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pnlMediaTitleDetail.add(pnlMediaTitleInfo, BorderLayout.NORTH);
        lblMediaTitleInfo = new JLabel();
        lblMediaTitleInfo.setText("Label");
        pnlMediaTitleInfo.add(lblMediaTitleInfo, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pnlMediaTitles = new JPanel();
        pnlMediaTitles.setLayout(new BorderLayout(0, 0));
        pnlMedia.add(pnlMediaTitles, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        pnlMediaTitles.add(scrollPane1, BorderLayout.CENTER);
        tableMediaTitles = new JTable();
        scrollPane1.setViewportView(tableMediaTitles);
        pnlLoadResource = new JPanel();
        pnlLoadResource.setLayout(new BorderLayout(0, 0));
        pnlMediaSelection.add(pnlLoadResource, BorderLayout.NORTH);
        btnChooseMedia = new JButton();
        btnChooseMedia.setText("...");
        pnlLoadResource.add(btnChooseMedia, BorderLayout.WEST);
        tfPath = new JTextField();
        tfPath.setText("");
        pnlLoadResource.add(tfPath, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        pnlMain.add(panel1, BorderLayout.SOUTH);
        pnlConnection = new JPanel();
        pnlConnection.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(pnlConnection, BorderLayout.SOUTH);
        pnlConnection.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "phpRecDB Website Connection", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnSendToPhpRecDb = new JButton();
        btnSendToPhpRecDb.setEnabled(false);
        btnSendToPhpRecDb.setHideActionText(false);
        btnSendToPhpRecDb.setIcon(new ImageIcon(getClass().getResource("/logo2.png")));
        btnSendToPhpRecDb.setText("");
        pnlConnection.add(btnSendToPhpRecDb, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Record URL:");
        pnlConnection.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        pnlConnection.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tfPhpRecDbUrl = new PlaceholderTextField();
        tfPhpRecDbUrl.setPlaceholder("paste PhpRecDB Record URL here");
        panel2.add(tfPhpRecDbUrl, BorderLayout.CENTER);
        btnConnect = new JButton();
        btnConnect.setText("connect");
        panel2.add(btnConnect, BorderLayout.EAST);
        btnPasteFromClipboard = new JButton();
        btnPasteFromClipboard.setText("paste from clipboard");
        panel2.add(btnPasteFromClipboard, BorderLayout.WEST);
        lblRecordInfo = new JLabel();
        lblRecordInfo.setText("");
        pnlConnection.add(lblRecordInfo, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Record:");
        pnlConnection.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.NORTH);
        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        pnlSnapshots = new JPanel();
        pnlSnapshots.setLayout(new BorderLayout(0, 0));
        panel3.add(pnlSnapshots, BorderLayout.CENTER);
        pnlSnapshots.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Snapshots", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        scrollbarSnapshots = new JScrollPane();
        scrollbarSnapshots.setHorizontalScrollBarPolicy(32);
        scrollbarSnapshots.setPreferredSize(new Dimension(10, 170));
        scrollbarSnapshots.setVerticalScrollBarPolicy(21);
        pnlSnapshots.add(scrollbarSnapshots, BorderLayout.CENTER);
        listSnapshots = new JList();
        listSnapshots.setLayoutOrientation(2);
        scrollbarSnapshots.setViewportView(listSnapshots);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        pnlSnapshots.add(panel4, BorderLayout.NORTH);
        btnSnapshot = new JButton();
        btnSnapshot.setText("snapshot");
        panel4.add(btnSnapshot);
        lblHelpSnapshots = new JLabel();
        lblHelpSnapshots.setText("-?-");
        panel4.add(lblHelpSnapshots);
        pnlRecordInfo = new JPanel();
        pnlRecordInfo.setLayout(new BorderLayout(0, 0));
        panel3.add(pnlRecordInfo, BorderLayout.WEST);
        pnlRecordInfo.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Record Info", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lblMediaInfo = new JLabel();
        lblMediaInfo.setText("Label");
        pnlRecordInfo.add(lblMediaInfo, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
